name: Lint & Test

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Update pip
        run: python -m pip install --upgrade --no-cache-dir pip
      - name: Update wheel
        run: python -m pip install --upgrade --no-cache-dir wheel
      - name: Update setuptools
        run: python -m pip install --upgrade --no-cache-dir setuptools
      - name: Install dev dependencies
        run: python -m pip install -r requirements-dev.txt
      - name: Run linters & friends
        run: make lint

  safety:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Update pip
        run: python -m pip install --upgrade --no-cache-dir pip
      - name: Update wheel
        run: python -m pip install --upgrade --no-cache-dir wheel
      - name: Update setuptools
        run: python -m pip install --upgrade --no-cache-dir setuptools
      - name: Install dev dependencies
        run: python -m pip install -r requirements-dev.txt
      - name: Analysing the dependencies with safety
        run: make safety

  unittests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Update pip
        run: python -m pip install --upgrade --no-cache-dir pip
      - name: Update wheel
        run: python -m pip install --upgrade --no-cache-dir wheel
      - name: Update setuptools
        run: python -m pip install --upgrade --no-cache-dir setuptools
      - name: Install dev dependencies
        run: python -m pip install -r requirements-dev.txt
      - name: Run unittests
        run: make test
